### ISSUE TITLE
Slot discovery may fail on single slot devices.

### ISSUE THREAD

**Issue by csnover** [not-a-feature/wd_fw_update#7]
Script tries to find the number of firmware slots but fails by trying to parse fw-log instead of looking at the frmw attribute? This does not work when there is only one firmware on the device and causes the script to try to commit the firmware to the currently active slot. Luckily this does not seem to work or it would probably brick devices due to the other issues in the script.

**Comment by not-a-feature** [comment]
The fw-log approach is used to get the corresponding fw version per slot.
A combined approach could be possible.

Pushing to an active slot is possible and works.

**Comment by not-a-feature** [comment]
TODO:
improve  get_model_properties to parse all properties
add test to check if all properties are loaded

**Comment by not-a-feature** [comment]
Fixed in https://github.com/not-a-feature/wd_fw_update/commit/3278da97777fe0e1e67c9da39a0360157471462c
